### ISSUE TITLE
How to catch Event on row selection?

### ISSUE THREAD

**Issue by ZedZipDev** [Mewriick/Blazor.FlexGrid#101]
How to catch row selection on click and call my own function?
For example,

user clicks on row, the row is selected and the row details displayed in other component.
user selects row and wants to download the object or print it etc.
Something like this is partially implemented in
https://github.com/gustavnavar/Grid.Blazor

It is
I.e. on row click OrderDetail component called.

**Comment by Mewriick** [comment]
Hello @Oleg26Dev 

you can use `OnItemClicked` event which is provided by FlexGrid

**Comment by ZedZipDev** [comment]
ok, thnx!
