### ISSUE TITLE
How to run demo?

### ISSUE THREAD

**Issue by ZedZipDev** [Mewriick/Blazor.FlexGrid#102]
I have downloaded the zip, unzipped it and try to run demo server, demo client. 
VS2019

But in both cases I see the simple page:

About
Hello, world!
Welcome to your new app.

No any errors in the log and in the VS output window.
What is wrong?

**Comment by Mewriick** [comment]
@Oleg26Dev 

if you set as Startup project Blazor.FlexGrid.Demo.Server do you see left navigation?

![image](https://user-images.githubusercontent.com/16129701/76324741-bceefb00-62e6-11ea-8fc1-7943a5dd9177.png)

**Comment by ZedZipDev** [comment]
Yes, its my mistake, I have rebuilt, run and it works. Спасибо
