### ISSUE TITLE
Disable edit on a line depending on the value of a column

### ISSUE THREAD

**Issue by Methraen** [Mewriick/Blazor.FlexGrid#107]
Hello @Mewriick 

If i have a column state for example, can i disable edit on lines that states equals false ?

**Comment by Methraen** [comment]
By the way, is it possible to put two arguments in the same column for example (name - description) ?

**Comment by Mewriick** [comment]
Hello @Methraen 

disable edit cannot be done by checking item status.

Yes you can put two arguments into one column you can use this functionallity in configuration 
`HasCompositeValueFormatter`
`HasBlazorComponentValueRender`

Or in razor page you can use

`BlazorComponentColumnCollection.AddColumnValueRenderFunction`

https://github.com/Mewriick/Blazor.FlexGrid/wiki/Custom-components-in-column
