### ISSUE TITLE
How to use  LazyLoadedTableDataAdapter with Master/Detail?

### ISSUE THREAD

**Issue by kalaur** [Mewriick/Blazor.FlexGrid#11]
How to use  LazyLoadedTableDataAdapter with Master/Detail?
Is there any example how to do this?
I have to use large data sets(approx 5k rows) and  CollectionTableDataAdapter just freezes on them

**Comment by Mewriick** [comment]
Hello,
now it is only possible use LazyLoadedTableDataAdapter only for first level of Master/Detail GridView.
So fo example you can have LazyLoadedTableDataAdapter for Persons but for their orders you must have CollectionTableDataAdapter .

I am working on this kind of limitaion.

**Comment by Mewriick** [comment]
Now you can find in demo project example of using LazyLoadedTableDataAdapter with Master/Detail
