### ISSUE TITLE
No results show empty grid as well as message.

### ISSUE THREAD

**Issue by MAndrade1980** [Mewriick/Blazor.FlexGrid#112]
Hi, we're running into another issue we are hoping you can shed some light on. When there are no results to display, a message is shown, which we can modify using the config. Is there a way to show the message but also show the empty grid? So show the grid with columns, and in the body show the empty list message?

**Comment by Mewriick** [comment]
Hello @MAndrade1980 
now there is not possibility render message and grid header. I will add this feature. It will be configurable via `HasEmptyItemsMessage`

**Comment by MAndrade1980** [comment]
Many thanks!

**Comment by Mewriick** [comment]
Hello @MAndrade1980 ,

new version is released. Please use new `HasEmptyItemsMessage(string message, bool renderGridHeader = true)` overload for desired behavior.

**Comment by MAndrade1980** [comment]
Looks great, thanks!
