### ISSUE TITLE
Case-insensitive filtering on non-lazy-loading scenario.

### ISSUE THREAD

**Issue by MAndrade1980** [Mewriick/Blazor.FlexGrid#113]
Hi, is there a way to do case-insensitive filtering without having to use the lazy-loading options?

**Comment by Mewriick** [comment]
Hello @MAndrade1980 

I need check this out because, if you use `TableDataSet` with filters, the filter expression is created from value which you put into filtering field.

**Comment by MAndrade1980** [comment]
Hi @Mewriick was just seeing if this was something that might be pushed in a near release? Also, would there be a section of the code I could peek at to see where this is going on? I would imagine this is some LINQ being used when filtering the DTO list.

**Comment by Mewriick** [comment]
Hi @MAndrade1980,
new version is released. This should now work aslo with `TableDataSet` without `LazyTableDataSet` need. 
In configuration method for column `IsFilterable` you can choose how text column will be matched during filtering part. Default value is `StringComparison.InvariantCultureIgnoreCase`

**Comment by MAndrade1980** [comment]
Looks great, many thanks!
