### ISSUE TITLE
FlexGrid inside EditForm - filter issues

### ISSUE THREAD

**Issue by MAndrade1980** [Mewriick/Blazor.FlexGrid#114]
Hi, when we are adding a flexgrid in a razor file inside of an EditForm element, any return clicks inside textboxes elsewhere on the page or button clicks seem to fire off the filtering on the first column. If I put the flexgrid outside of the EditForm, it goes away. We have instances where the grid is sitting in the middle of large forms inside of an EditForm. Is there a way to not have the filtering execute like this when a submit is invoked inside the EditForm?

**Comment by MAndrade1980** [comment]
![FlexGrid-EditForm-Filtering-Issue](https://user-images.githubusercontent.com/5994524/94842761-c4443600-03e9-11eb-9c44-1fb01ed8c060.png)

**Comment by Mewriick** [comment]
@MAndrade1980 
Can you please show me some example, because I cannot simulate this problem.

**Comment by MAndrade1980** [comment]
[BlazorApp1.zip](https://github.com/Mewriick/Blazor.FlexGrid/files/5318283/BlazorApp1.zip)

I've attached a demo of the issue on a new blazor WASM project. If you build the project and run it, you'll see a simple form with a textbox and a grid. They are both in an EditForm, if you click on the textbox, leaving it empty, and just hit Enter, you'll notice it fires the grid filter along with notifying you the field is required. If you take the grid out of the EditForm it will work as it should. Let me know if you need anything else to troubleshoot!

**Comment by MAndrade1980** [comment]
Hi @Mewriick was just looking to see if there was any progress on this issue?

**Comment by Mewriick** [comment]
Hello @MAndrade1980 , 
sorry I had no time, but this weekend I will look on this and I hop next week will be release

**Comment by MAndrade1980** [comment]
Hi @Mewriick that sounds great, I look forward to seeing a new release!

**Comment by Mewriick** [comment]
Hi @MAndrade1980 
new version is released, this issue should be fixed

**Comment by MAndrade1980** [comment]
Looks great, many thanks!
