### ISSUE TITLE
is there work in progress or is this abandoned?

### ISSUE THREAD

**Issue by agonzalezm** [Mewriick/Blazor.FlexGrid#13]
Hi, I was planning using this for one small app i have to write but as i dont see new commits in more than 2 months or work in progress just wanted to check if there is a new version coming for blazor 0.6 and if new features and bugs are being worked on?

Thanks!

**Comment by Mewriick** [comment]
Hello,

I had difficult time so I did not have much time for this project. I will start to developing new features & upgrading for Blazor 0.6 next week so this project is not abandoned.

**Comment by agonzalezm** [comment]
thanks! hope to see new update soon!

**Comment by agonzalezm** [comment]
@Mewriick there is gitter channel for blazor extensions https://gitter.im/BlazorExtensions/Lobby and https://github.com/BlazorExtensions for people working on components/extensions to follow same patterns and namespaces and put them together for easy discoverability.

Would be great to see your component under BlazorExtensions.
