### ISSUE TITLE
Using LazyRequestParams

### ISSUE THREAD

**Issue by pdavis68** [Mewriick/Blazor.FlexGrid#14]
Am I correct in my understanding that the LazyRequestParams are additional parameters sent in the Lazy Loading requests? 

Given the following grid setup:

```
@addTagHelper *, Blazor.FlexGrid
@using Blazor.FlexGrid.DataAdapters
@using Blazor.FlexGrid.DataSet
@using Blazor.FlexGrid.DataSet.Options
@using Blazor.FlexGrid.Components.Configuration
@using Blazor.FlexGrid.Components
@using EmployeeDirectory.Shared
@page "/"
@inject HttpClient Http
@inject LazyLoadedTableDataAdapter<Employee> employeeAdapter

<div>
    <GridView DataAdapter="@employeeAdapter" LazyLoadingOptions="@(new LazyLoadingOptions() { DataUri = "/api/Employee/GetEmployeeRange" })" PageSize="10"></GridView>
</div>


@functions
{
    protected override void OnInit()
    {
        base.OnInit();
    }
}
```

How would I implement the LazyRequestParams? The employeeAdapter doesn't exist at the point on OnInit(). I'm still kind of new to Blazor, so I'm not sure what the entire lifecycle is of the various pieces. 
What I'm trying to accomplish is to add a free-text search that will then be used to filter the results before populating the grid, So I'm thinking of something along the lines of:

```
        LazyRequestParams lrp = new LazyRequestParams();
        lrp.AddParam("Search", "SearchString");
        employeeAdapter.AddRequestParamsAction(lrp);
```
I'm just not sure at what point I should be doing this.

Thanks.

**Comment by pdavis68** [comment]
Thought I might have had it doing this:

```
@addTagHelper *, Blazor.FlexGrid
@using Blazor.FlexGrid.DataAdapters
@using Blazor.FlexGrid.DataSet
@using Blazor.FlexGrid.DataSet.Options
@using Blazor.FlexGrid.Components.Configuration
@using Blazor.FlexGrid.Components
@using EmployeeDirectory.Shared
@page "/"
@inject HttpClient Http

<div>
    <GridView DataAdapter="@employeeAdapter" LazyLoadingOptions="@lazyLoadingOptions" PageSize="10"></GridView>
</div>


@functions
{
    [Inject]
    LazyLoadedTableDataAdapter<Employee> employeeAdapter { get; set; }
    LazyLoadingOptions lazyLoadingOptions { get; set; }

    protected override void OnInit()
    {
        lazyLoadingOptions = new LazyLoadingOptions()  { DataUri = "/api/Employee/GetEmployeeRange" };
        lazyLoadingOptions.RequestParams.AddParam("Search", "SearchString");
        base.OnInit();
    }
}
```

But I'm not seeing the parameter in the request.  

What am I missing?

**Comment by Mewriick** [comment]
Hello

you are correct, but I have little bug in GridViewInternal class so I have to fix it (today afternoon I will fix it).
Originally LazyRequestParams are designed for internal purposes (Master/Detail filtration) and preparation for filtering feature which I am now focusing on.

**Comment by pdavis68** [comment]
What is the change that needs to be made so that I can make it in my local copy. 

Thanks.

**Comment by Mewriick** [comment]
Here is the commit with fix
https://github.com/Mewriick/Blazor.FlexGrid/commit/201c52772f77bc1bb6ce353f5dae303a9af476ea

**Comment by pdavis68** [comment]
Thank you! That got it! 
Very nice grid, by the way. I love the design. Still trying to more fully wrap my head around it, but it's very clean and very nicely laid out from what I can tell so far.

Do you have any plans to add editing?

**Comment by Mewriick** [comment]
Thanks I am glad that you like the grid. Yes ofcourse i plan inline editing in grid, but now I am focusing on filtering part. I will try to add editing as soon as possible.

**Comment by pdavis68** [comment]
Very cool. I will try to get more acquainted with the architecture so that maybe I can pitch in and assist you.
