### ISSUE TITLE
How would I create a non-text column

### ISSUE THREAD

**Issue by pdavis68** [Mewriick/Blazor.FlexGrid#16]
I want to have columns that render something besides text (buttons, arbitrary HTML, etc). How would I go about that?

**Comment by Mewriick** [comment]
For now it is not possible, I will add this feature

**Comment by pdavis68** [comment]
Could I not use the ValueFormatter? Or will that encode markup? 

This might be something I could help out with, if you wouldn't mind help. Do you have an idea for how you would want it implemented?

**Comment by Mewriick** [comment]
After this commit https://github.com/Mewriick/Blazor.FlexGrid/commit/0e50b94db199fb4a6fb266b0aabbb3754bd67d30
you cau use ValueFormatter and HTML will be rendered correctly.

Nuget version will be released afterwards

**Comment by pdavis68** [comment]
That's terrific. Thanks.
