### ISSUE TITLE
HasValueFormatter should have access to the full object.

### ISSUE THREAD

**Issue by IvanJosipovic** [Mewriick/Blazor.FlexGrid#17]
It would be awesome if the HasValueFormatter had access to the whole column object instead of one property.
This would allow for more complex scenarios such as composing urls which require a url and title or passing the column object to a component.

Example:
```
namespace Blazor.FlexGrid.Demo.Client.GridConfigurations
{
    public class DataObject
    {
        string title { get; set; }

        string url { get; set; }
    }


    public class DataObjectGridConfiguration : IEntityTypeConfiguration<DataObject>
    {
        public void Configure(EntityTypeBuilder<DataObject> builder)
        {
            builder.Object()
                .HasCaption("Title")
                .HasOrder(1)
                .HasValueFormatter(s => $"<a href='{s.url}'>{s.title}<a/>");

            builder.Object()
                .HasCaption("Details")
                .HasOrder(2)
                .HasValueFormatter(s => $"<SomeComponent Data='{s}'><SomeComponent/>");
        }
    }
}

```

**Comment by Mewriick** [comment]
I will look at this, but I think that HasValueFormatter have to acces to the row object. The ValueFormatter must be connected with propertyName because the value must be rendered in correct column. I will definitelly think how to solve this good idea for improvement.

**Comment by Mewriick** [comment]
In this commit https://github.com/Mewriick/Blazor.FlexGrid/commit/cdf9999827d24519ba7be39066656d1288f5d1a2
is my proposal are you OK with this? Or suggests some improvement?

**Comment by IvanJosipovic** [comment]
Thanks for the quick response.

I tested the changes and the implementation is very promising. 

I did find that it does not work with blazor components. In my test I tried to use the BlazorButton from the BlazorStrap project and it wouldn't render.

```
public void Configure(EntityTypeBuilder<StoreListItem> builder)
{
	// This works fine!
	builder.Property(e => e.ProductsDeleted)
		.HasOrder(1)
		.IsSortable()
		.HasCaption("Deleted")
		.HasCompositeValueFormatter(item => $"<div class='{((double)item.ProductsDeleted / item.Products > 0.2 ? "text-danger font-weight-bold" : "")}'>{item.ProductsDeleted}</div>");
	
	// This does not work
	builder.Property(e => e.UrlTests)
		.HasOrder(2)
		.IsSortable()
		.HasCaption("Url Tests")
		.HasCompositeValueFormatter(item => "<BlazorButton>Test</BlazorButton>");

}
```

**Comment by Mewriick** [comment]
I see the problem with Blazor components, and it will be more difficult because you can configure these components and HasCompositeValueFormatter it will have to deal with this.

**Comment by Mewriick** [comment]
In this https://github.com/Mewriick/Blazor.FlexGrid/commit/13cfaccbd391a3950f9119bdcce2fb1d204ba785 commit is my suggestion to render blazor components in column.

You have to configure this by using `BlazorComponentColumnCollection` and associate `RenderFragment` with right column name by using `AddColumnValueRenderFunction` method. You can see it in commit.
