### ISSUE TITLE
DataAdapter directly from DataTable

### ISSUE THREAD

**Issue by kalaur** [Mewriick/Blazor.FlexGrid#2]
Create a DataAdapter directly from the DataTable.
If this is possible then how to do i?

**Comment by Mewriick** [comment]
Hello,
now it is possible create your own DataAdapter by creating class which implements interface `ITableDataAdapter`. Also you can create your own DataSet object which provide list of items to the Grid component by creating class which implements interface `ITableDataSet`.

If you want create your own TableDataSet you must also create DataAdapter which create this DataSet object for Grid component.

**Comment by kalaur** [comment]
I made a working sample of FlexGrid with DataTable.
May I create a pull request for it?

**Comment by Mewriick** [comment]
Yes sure I will check it :-) I am on vaciton till Monday and in Monday I will check it.

**Comment by mblataric** [comment]
Hi, 

can you share FlexGrid with DataTable? 
I would also like to try this out in server-side Blazor. 

Thanks, 
Mario

**Comment by kalaur** [comment]
Hi,
Sure.How to do it in the best way?
Pull request?
I also implement authorization when querying through ASOS
I can add this code if you are interested

**Comment by mblataric** [comment]
> Hi, Sure.How to do it in the best way? Pull request? I also implement authorization when querying through ASOS I can add this code if you are interested

Pull request is probably the best. 
I can see the code and @Mewriick can check it out and decide whether to include it in the project.

**Comment by kalaur** [comment]
Hi,
take a look at my fork, if anything is not clear, contact to me
https://github.com/kalaur/Blazor.FlexGrid
