### ISSUE TITLE
Blazor 0.8.0 support

### ISSUE THREAD

**Issue by IvanJosipovic** [Mewriick/Blazor.FlexGrid#34]
Blazor 0.8.0 was just released
https://blogs.msdn.microsoft.com/webdev/2019/02/05/blazor-0-8-0-experimental-release-now-available/

**Comment by Mewriick** [comment]
I do not know if it is good to be depend on preview version, especially if you need VS 2019.

**Comment by IvanJosipovic** [comment]
Thank you!
