### ISSUE TITLE
Unused assets bloating dll size

### ISSUE THREAD

**Issue by alek-mcgarry** [Mewriick/Blazor.FlexGrid#43]
So I noticed that FlexGird.dll was taking 2.5MB which was more than mscorlib.dll and mono.wasm which seemed odd

Looks like a bunch of fontawesome thing being embedded into it

I don't know what the grid uses but I'm pretty sure the dll size could be reduced by like 90%

**Comment by Mewriick** [comment]
Thanks, I will check it

**Comment by Mewriick** [comment]
I hope that in new version is it better. If you have any ideas how to improve this problem do not hesitate to advice me. Thanks
