### ISSUE TITLE
Background color for next/prev page row

### ISSUE THREAD

**Issue by spac3cas3** [Mewriick/Blazor.FlexGrid#45]
Is it possible to specify in some way which background color should be on the row with first/prev/next/last page row? 

In my application now it defaults to white with a black background on the next/last page buttons. I have tried all kinds of things in css etc to change that black background, but no luck. See attached screenshot. 

![image](https://user-images.githubusercontent.com/47597323/54093980-81e97d00-439d-11e9-8d03-530649acf07e.png)

**Comment by Mewriick** [comment]
Hello,

for now there is no possibility to change pagination css styles. I will add this feature into next bigger release which will coming this week (I hope on wednesday or thursday)

**Comment by Mewriick** [comment]
With new verison of nuget you can use:

```
builder.AppendCssClasses(conf =>
{
    conf.FooterCssClasses.FooterWrapper = "cssClassName";
});
```
