### ISSUE TITLE
Grid styling not included in NuGet package install

### ISSUE THREAD

**Issue by aford22** [Mewriick/Blazor.FlexGrid#49]
Hello - I installed your package Blazro.FlexGrid via NuGet into my Razor Components .net core 3 preview 3 project. The flexgrid works, but it has no css styling at all.

To fix this I had to:
1) Download FlexGridStyles.css from this GitrHub repo
2) Add the following to my index.cshtml:     <link rel="stylesheet" href="~/css/Blazor.FlexGrid/FlexGridStyles.css" />

After that, the FlexGrid is now styled properly

**Comment by Mewriick** [comment]
Hello @aford22 I know about this issue, but unfortunately I do not have solution for this. If you have any idea it will be great to help me with this issue.

**Comment by aford22** [comment]
Hi there. I am not an expert on any of this so don't have anything helpful to give you, sorry :-(

Except that it would be good to document this extra step in your installation instructions. At least that way others won't hit the same problem?

**Comment by Mewriick** [comment]
@aford22 Yeah I will add this into README. This issue only occurs with Razor Components, with web assembly it works correctly. Nuget contatin folder contents with this required styles and fotns, but in Razor Components they are not included in HTML

**Comment by larshg** [comment]
@Mewriick Maybe you can do like [ChartJs](https://github.com/mariusmuntean/ChartJs.Blazor/blob/master/src/ChartJs.Blazor/ChartJsBlazor.cs) until a official solution is released.

This only copies the values to the hosting project, but works ok for a temporary solution.

**Comment by Mewriick** [comment]
@larshg Thank you so much! I will try it today.

**Comment by Mewriick** [comment]
New verison of nuget copies the content to the hosting project & README is updated with steps what to do for server side projects

@larshg Big thanks
