### ISSUE TITLE
Blazor Server project - I would like to specify columns (including edit and delete icons)

### ISSUE THREAD

**Issue by shanthuk** [Mewriick/Blazor.FlexGrid#51]
I really love this component. However, I do not know how I can explicitly specify columns in the "view" (razor file). Along with data columns, I would like to add "Edit" and "Delete" icons. These icons should fire the corresponding events as well ( onEdit or onDelete etc.)

**Comment by Mewriick** [comment]
Hello @shanthuk
 I am very glad that you like the component. 
I do not know if I understand correctly to your question, but for adding Edit & Delete icons for row you have to use builder method in configuration for the grid.

Example:
```
builder.AllowInlineEdit(conf =>
{
    conf.AllowDeleting = true;
}
```

If you want to specify columns which can appear in inlie editing for row, you have now only permission restricions for columns.

```
builder.Property(c => c.Email)
  .HasReadPermissionRestriction(perm => perm.IsInRole("Read"))
  .HasWritePermissionRestriction(perm => perm.IsInRole("Write"));
``` 

If I badly understood your question I am apologize to you.
