### ISSUE TITLE
How do i make this grid work with .NET Core 2.1

### ISSUE THREAD

**Issue by sanzor** [Mewriick/Blazor.FlexGrid#54]
Can i use .NET Core 2.1 with this grid ? So far i get an error on mismatch of `Microsoft.AspNetCore.Authorization `

> Error	NU1107	Version conflict detected for Microsoft.AspNetCore.Authorization. Install/reference Microsoft.AspNetCore.Authorization 3.0.0-preview6.19307.2 directly to project UIAdmin.Server to resolve this issue.

**Comment by Mewriick** [comment]
Hello @sanzor 

unfortunately you cannot use this nuget with .NET Core 2.1 because it targets 3.0.0.-preview6.19307.2 version.
If you are using it on server side due to types which are supporting for Http request I can separate this kind of types into another nuget which will target .NET Standard.

**Comment by sanzor** [comment]
Hello @Mewriick ,
Thank you for your reply. I have managed to create something similar to a .NET Grid working with .NET Core 2.1. I am using client side .
