### ISSUE TITLE
builder.AllowCreateItem possible for us to use Jeremy Skinner's FluentValidation?

### ISSUE THREAD

**Issue by githubfanster** [Mewriick/Blazor.FlexGrid#60]
I notice that FlexGrid has an automatic way to create forms (via builder.AllowCreateItem()) with validation and submit button.

Our model / data validation needs sometimes involve cross-field validations. Is there a current approach for doing this? Can we somehow hook up Jeremy Skinner's FluentValidation (https://github.com/JeremySkinner/FluentValidation) into and for use with the create forms auto-generated by FlexGrid instead of the built-in validator (is it Blazor's DataAnnotationValidator?) in cases where we need to?

Thanks for helping!

**Comment by Mewriick** [comment]
Hello @githubfanster 

FlexGrid use standard Blazor `EditContext` for validation of model in create item form

https://github.com/aspnet/AspNetCore/blob/master/src/Components/Components/src/Forms/EditContext.cs

And this context use standard `ValidationContext`. 
So you can use `IValidatableObject` wich will implement your model. And implement `Validate` method and in this method you can use your configured FluentValidator. 

This is for now only possible solution.

**Comment by githubfanster** [comment]
Ok, thanks!

Other questions re: Create Forms.

In your Server-Side Blazor demo, WeatherForecast grid's '+' button when clicked, pops up a Modal Create Form.  But in my case, once my grid is displayed, the CreateForm is displayed below it already. Can this be controlled (my grid may contain several items, so it might be better if the Create Form pops up only when needed)?

Also, when the Create Form is already displayed below my grid upon initial display, when i click on the 'X' button, the Create Form disappears but I can't bring it back again by clicking the '+' button in the grid. Is this the current behavior?  Can this be changed?

Thanks!

**Comment by Mewriick** [comment]
@githubfanster 

The CreateItemForm should be now always as popup dialog. Only in HTML is rendered below the grid.
Co if you after create button click popup is not displayed thats a problem.
Can you please show me some screenshots or gif with tihs behavior?

Thanks!

**Comment by githubfanster** [comment]
here's the screenshot in PNG format.
i checked the version of the FlexGrid software I was using and the download date was Jul
[FlexGridCreateItemForm.zip](https://github.com/Mewriick/Blazor.FlexGrid/files/3431524/FlexGridCreateItemForm.zip)
y 22

**Comment by Mewriick** [comment]
@githubfanster 
Can you plase sned me the HTML source of this page for better understanding whats going on?
Especially the create form section.
Thanks!

**Comment by githubfanster** [comment]
I'm sending you the entire project because it is just a learning wheels project.
I'm basically trying to learn FlexGrid by converting Jimmy Bogard's ContosoUniversityDotNetCore-Pages to using Blazor (https://github.com/jbogard/ContosoUniversityDotNetCore-Pages)

Only the "Students" feature is working right now more or less.

Right before I zipped my solution, I tried it with the latest FlexGrid version (the one you released 10+ hours ago incorporating Blazor Preview 7 ). I'm still seeing the same behavior (the Create Item Form displaying below the FlexGrid on initial display).

Another thing I noticed is that for EnrollmentDate input, the DatePicker is not coming up (when i click on the calendar icon, the calendar widget is not displaying. this is different experience from your demo).

The solution consists of 3 projects. Only two projects are included in the attached zip file. (the missing 3rd is the Blazor.FlexGrid project, so you have to add this for the solution to work)

Thanks for looking into this as well as the new  "datepicker" problem mentioned here.


[ContosoUBlazor04-BasicCRUDStudents.zip](https://github.com/Mewriick/Blazor.FlexGrid/files/3434329/ContosoUBlazor04-BasicCRUDStudents.zip)

**Comment by githubfanster** [comment]
Hello!

I started over by creating an out of the box Server-Side Blazor app, and the only thing I did differently was to leave the files in the Shared folder (MainLayout.razor,  NavMenu.razor), and the site.css basically unchanged from the original except for adding a link to my Students.razor in NavMenu.

The CreateItemForm  is working similarly to your Server-Side Demo now.  Clicking the grid's '+ ' button brings up the CreateItemForm and clicking the 'datepicker' icon in that form brings up the calendar widget, etc.

Any idea why mucking with the files in the Shared folder and the site.css  could have caused my problems?  Does this make possible sense to you, or am i not even close? If it makes some sense, could you please take a quick look at those files in the zip file I sent you?  I'm just curious so I dont inadvertently make the same mistake again.

It would be nice to know what might have caused my problem.  :-)

Thanks for helping and sorry for taking up your time!

**Comment by Mewriick** [comment]
The problem is probably caused due too bad scripts loaded, because in earlier versions of FlexGrid you have to manually put css, js files into wwwroot folder when you are using Server side Blazor. In some version I added extension method `UserFlexGrid `

https://github.com/Mewriick/Blazor.FlexGrid/blob/master/src/Blazor.FlexGrid/ApplicationBuilderExtensions.cs

which copy these files automatically. This is required only if you are using Server side Blazor becasue Microsoft does not have solved this copy files problem.

**Comment by githubfanster** [comment]
Not sure I understand the problem. 

Is it sort of similar to this:
https://github.com/aspnet/AspNetCore/issues/7300
The blazor component library (dotnet new blazorlib) is not working properly with razor components (blazor server side). Specifically the static files that are embeded in the library are not served when the page is loaded.

and SQL-MisterMagoo's Razor Components BlazorEmbedLibrary addresses

SQL-MisterMagoo commented on Mar 6
@stavroskasidis
Until the Microsoft team get this working, I have written a project that brings this functionality back for Razor Components BlazorEmbedLibrary
If you add this to your App, it will embed the static CSS and JS files at runtime into the head of your app using browser blob storage.
You might find it useful as a workaround.


Also, I saw this note from Chris Sainty in https://github.com/Blazored/Modal:

Important Notice for Blazor Apps Regarding the CSS Content in Blazored Toast
As of ASP.Net Core Preview 6 content can be embedded in a Razor class Library. However there were two outstanding issues that prevent easy use of said content. These were resolved in Preview7. You should add:

<link href="_content/Blazored.Modal/blazored-modal.css" rel="stylesheet" />

To your index.html (client side) or _Host.cshtml (server side). This is what is included in both the BlazorSample project as well as the BlazorServerSideSample project.

**Comment by Mewriick** [comment]
Yes this is the problem, I also have section in README https://github.com/Mewriick/Blazor.FlexGrid#setup-blazor-app-as-razorcomponents-aka-serverside-blazor-app where is described how to handle this. FlexGrid extensions UseFlexGrid also solve this problem without any manual copying files.

**Comment by githubfanster** [comment]
Ok. Thanks!
