### ISSUE TITLE
The type or namespace name 'FlexGrid' does not exist in the namespace '' (are you missing an assembly reference?)	

### ISSUE THREAD

**Issue by aherrick** [Mewriick/Blazor.FlexGrid#61]
I've updated to the latest Preview  7 bits but I cannot seem to have the namespace resolved. I have the linker file as well. What am I doing wrong here?

![7-26-2019 11-05-04 AM](https://user-images.githubusercontent.com/586671/61961346-45599f00-af95-11e9-995e-38549cc81da9.png)

![7-26-2019 11-02-00 AM](https://user-images.githubusercontent.com/586671/61961217-10e5e300-af95-11e9-98e3-028921048c73.png)

**Comment by Mewriick** [comment]
Hello @aherrick 

I can see that `AddFlexGrid` extensions method is resolved ok. Do you have properly update both Client & Server project to lates blazor nuget packages? I do not see any mistake. Do you have properly installed all prerequisites (VS update, SKD.. )?

**Comment by aherrick** [comment]
Yes all updates are in place. Agreed the AddFlexGrid is resolving but there is no Server project at this point it's a fully client project. So i'm wondering what else could be wrong? I'm on the latest VS 2019 Preview all updates and Preview 7.

**Comment by Mewriick** [comment]
Maybe the problem is that your namespace is ends with `Blazor ` word

**Comment by aherrick** [comment]
It appears that was the issue... I would think I should be able to have "Blazor" in my namespace..... perhaps it's not good to have the project "Blazor.FlexGrid" ?

**Comment by Mewriick** [comment]
I think that the name of project is not bad. You can have Blazor in your namespace but it can not be in the end of the namespace.  For exmaple XXX.Blazor.XXX will work also my namespace Blazor.FlexGrid.Demo.Client is ok

**Comment by aherrick** [comment]
But it wasn't at the end. The end was "Client"

**Comment by Mewriick** [comment]
Yeah I see maybe another problem with Blazor.Client is that Microsoft has this namespace and there is conflict too. I hope that change of namespace name help to solve your problem
