### ISSUE TITLE
Trigger Reload to Fetch Data with Lazy

### ISSUE THREAD

**Issue by aherrick** [Mewriick/Blazor.FlexGrid#62]
I have code like this. When I click Apply Filters I want the grid to fire back to the API endpoint with the added Request Parm. How do I do this?

```
<form class="form-inline">
	<div class="form-group mb-2">
		<label for="temp">Temp</label>
		<input type="text" class="form-control" @bind="@Name" />
	</div>

	<button type="button" onclick="@ApplyFilters" class="btn btn-primary mb-2">Apply Filters</button>
</form>

<GridView DataAdapter="@forecastAdapter" LazyLoadingOptions="@lazyLoadingOptions" PageSize="10"></GridView>

@code {

	LazyLoadingOptions lazyLoadingOptions { get; set; }
	private string Name { get; set; };

	protected override async Task OnInitAsync()
	{
		lazyLoadingOptions = new LazyLoadingOptions() { DataUri = "https://localhost:44366/demo/WeatherForecasts" };
	}

	private void ApplyFilters()
	{
		lazyLoadingOptions.RequestParams.Add("Search", "SearchString");
	}
}

```

**Comment by Mewriick** [comment]
Hello @aherrick 

waht you want to accomplish by this scenario? If you want to filter by this value you can use filter API which FlexGrid provide.

**Comment by aherrick** [comment]
Hi @Mewriick I don't want/need to use the built in table filtering. For example I may have a field that isn't showing or used in the grid that I simply want to filter by.

I'm just simply trying to force a callback.

**Comment by Mewriick** [comment]
Ok, unfortunately now there is not such a feature to force call API when you click your button.

**Comment by Mewriick** [comment]
Only solution now maybe is 

```cs
	private void ApplyFilters()
	{
		lazyLoadingOptions = lazyLoadingOptions.RequestParams.Add("Search", "SearchString");
	}
```

which should invoke `OnSetParameterAsync`  method in FlexGrid and ther is call to go to first page which invoke API call.

**Comment by aherrick** [comment]
Resetting lazyLoadingOptions in this way isn't valid.

![7-28-2019 9-38-32 AM](https://user-images.githubusercontent.com/586671/62007451-867bbb80-b11b-11e9-8975-848cb086217b.png)

**Comment by Mewriick** [comment]
Yeah, I see it now. So basically you can do this:

```cs
private void ApplyFilters()
{
	lazyLoadingOptions = new LazyLoadingOptions()
        { 
             DataUri = lazyLoadingOptions .DataUri,
             PutDataUri = lazyLoadingOptions.PutDataUri,
             DeleteUri = lazyLoadingOptions.DeleteUri 
        }.RequestParams.Add("Search", "SearchString");
}
```

**Comment by aherrick** [comment]
Hmm so I'm trying even this and still isn't forcing a server call:

```
	private void ApplyFilters()
	{
		lazyLoadingOptions = new LazyLoadingOptions()
		{
			DataUri = lazyLoadingOptions.DataUri
		};
	}
```

**Comment by Mewriick** [comment]
> The OnParametersSet and OnParametersSetAsync methods are called when a component is first initialised and each time new or updated parameters are received from the parent in the render tree.

your scenario is that object is still same

**Comment by aherrick** [comment]
I've tried below which doesn't work.

```
	lazyLoadingOptions = new LazyLoadingOptions()
		{
			DataUri = lazyLoadingOptions.DataUri
		};
		lazyLoadingOptions.RequestParams.Add("test", "test");
```

While this throws errors:
```

		lazyLoadingOptions = new LazyLoadingOptions()
		{
			DataUri = lazyLoadingOptions.DataUri
		}.RequestParams.Add("test", "test");
```

Is there a different way to Initialize the object and set the request parameters at the same time?

**Comment by Mewriick** [comment]
I think you can do this

```cs
var secondLazyLoadingOptions = ..... ;
lazyLoadingOptions  = secondLazyLoadingOptions ;
```

**Comment by aherrick** [comment]
Unfortunately that doesn't work either:

```
	private void ApplyFilters()
	{
		var secondLazyLoadingOptions = new LazyLoadingOptions()
		{
			DataUri = lazyLoadingOptions.DataUri,
		};
		secondLazyLoadingOptions.RequestParams.Add("test", "test");

		lazyLoadingOptions = secondLazyLoadingOptions;
	}
```

Not sure how you fill the `RequestParams` in initialization as it's a `get `only property.

**Comment by Mewriick** [comment]
Ok I think that `OnParametersSetAsync` of FlexGrid is called but some conditions are false and method which call API is not called. This is not supported scenarion and this is only hack so this can not be done now

**Comment by aherrick** [comment]
Ok, unfortunately it's a deal breaker for me then to use the Grid.

**Comment by Mewriick** [comment]
Yeah Ok, also you can suggest how to solve this and use pull request.

**Comment by Mewriick** [comment]
@aherrick 

Version 0.11.0 contains new feature which you can use for refreshing grid view. See the [wiki](https://github.com/Mewriick/Blazor.FlexGrid/wiki/Triggers)
