### ISSUE TITLE
Support Preview 8

### ISSUE THREAD

**Issue by IvanJosipovic** [Mewriick/Blazor.FlexGrid#66]
See Blog for details:
https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-8

**Comment by Behnam-Emamian** [comment]
There are few errors:
1) BindMethods.GetEventHandlerValue
2) RenderTreeBuilder.ChildContent
3) RuntimeHelpers.TypeCheck
