### ISSUE TITLE
any feature for dropdown list from List<>?

### ISSUE THREAD

**Issue by nikitwei** [Mewriick/Blazor.FlexGrid#68]
Hi Jaroslav, 
many thanks for your great job in this project.

I am new in .Net Core. now im in my first project and using your library is very interesting and helpful.
I interst with how you render enum automaticly to dropdown list. Im trying to follow your code to make modification so i can do the same to List<>, but still got error. 

basicly, this is my first project and first job, so thanks again for this great library. I am glad if you can help or add new feature for this.

BR, Nikitwei!

**Comment by Mewriick** [comment]
Hello @nikitwei 

I basically build renderer tree for `select` input with `onchange` event.  Input contains `option` elemetns. `option` element has `selected` attribute and also `value` attribute. 

Example:

```cs
rendererTreeBuilder
	.OpenElement(HtmlTagNames.Div, "edit-field-wrapper")
	.OpenElement(HtmlTagNames.Select, "edit-text-field")
	.AddAttribute(HtmlJSEvents.OnChange, EventCallback.Factory.Create(this,
		(UIChangeEventArgs e) =>
		{
                    // Here is code which you want execute after value in input is changed
		}
	));
// Here you can iterate your List<> or Dictionary<> where enumStringValue you replace with your 
// value and enumStringValue you replace with texh which you want show to user
foreach (var enumValue in Enum.GetValues(enumTypeValue.GetType()))
{
	var enumStringValue = enumValue.ToString();

	rendererTreeBuilder.OpenElement(HtmlTagNames.Option);
	if (enumStringValue == actualStringValue)
	{
		rendererTreeBuilder.AddAttribute(HtmlAttributes.Selected, true);
	}

	rendererTreeBuilder
		.AddAttribute(HtmlAttributes.Value, enumStringValue)
		.AddContent(enumStringValue)
		.CloseElement();
}

rendererTreeBuilder
	.CloseElement()
	.CloseElement();
```

You can also send me your code with errors and we can handle it.
I am glad that you like this component, Thanks!

Now the List<> works as Master/Detail scenario

BR, Jaroslav
