### ISSUE TITLE
Reload Grid

### ISSUE THREAD

**Issue by justborg** [Mewriick/Blazor.FlexGrid#73]
Is there a way to rebind the grid? or change the data adapter at runtime?

**Comment by Mewriick** [comment]
Hello,
No there is not such option to rebind grid at runtime.

**Comment by justborg** [comment]
Hi,
Thanks for your quick reply.

One more question, is it possible to filter the result programmatically when using the standard adapter (not lazy loading) i.e. dataAdapter.Filter?



Thanks in advance :)

**Comment by Mewriick** [comment]
Only one possible solution is:
```cs
       var dataAdapter = new CollectionTableDataAdapter<WeatherForecast>);
        dataAdapter.Filter = w => w ...
```

This will be only working for first setup of grid.

**Comment by mswietlicki** [comment]
@justborg  Regarding your first question. You can always hack rebinding by destroying the grid and rebuilding it.  

```
@if (dataAdapter != null) { <GridView ... ? /> }

...

dataAdapter = null;
StateHasChanged();
dataAdapter = new CollectionTableDataAdapter<...
```

**Comment by Mewriick** [comment]
@justborg 

Version 0.11.0 contains new feature which you can use for rebind the data adapter for grid. See the [wiki](https://github.com/Mewriick/Blazor.FlexGrid/wiki/Triggers)
