### ISSUE TITLE
How can i set a specific edit input on a column ?

### ISSUE THREAD

**Issue by Methraen** [Mewriick/Blazor.FlexGrid#85]
One of those edits inputs for example : Blazor.FlexGrid/src/Blazor.FlexGrid/Components/Renderers/EditInputs/

**Comment by Methraen** [comment]
I tried a lot of strange things like this :

`Func<EditColumnContext, RenderFragment<TestDto>> ConMatEditForm =
                 context =>
                 {
                   RenderFragment<TestDto> EditFormBuilder = (TestDto test) => delegate (RenderTreeBuilder rendererTreeBuilder)
                   {
                      new CheckBoxInputBuilder().BuildRendererTree<TestDto>(null, null);
                   };
                   return EditFormBuilder;
                 };`

I would actually really appreciate some help in a close future...

**Comment by Mewriick** [comment]
@Methraen 
I close this one and we solve this issue in https://github.com/Mewriick/Blazor.FlexGrid/issues/86
