### ISSUE TITLE
feature request: use autorization

### ISSUE THREAD

**Issue by kalaur** [Mewriick/Blazor.FlexGrid#9]
in LaazyLoadGrid add use autorization, use tokens oauth/jwt

**Comment by Mewriick** [comment]
I am sorry for that this feature take long time but here is my proposal  https://github.com/Mewriick/Blazor.FlexGrid/commit/8de85b8353befe867fe452eed71eec16b8f0c840
Any suggestions for improvements?

**Comment by kalaur** [comment]
Is any example how to use it?
