### ISSUE TITLE
Apply automatically a filter on a grid

### ISSUE THREAD

**Issue by Methraen** [Mewriick/Blazor.FlexGrid#95]
@Mewriick 
Is it possible ?
Like, in the builder, for a string column, to specify an alphabetical filter to apply directly ?

**Comment by Mewriick** [comment]
@Methraen 
unfortunately this is not possible now. If you have `CollectionDataAdapter` you can apply fillter before you pass into constructor. If you have `LazyLoadedDataAdapter` you can do this in server. Maybe I will consider to add this feature.

**Comment by Methraen** [comment]
Thank you for your fast answer, i'll try to filter before passing into constructor as you said, have a good day.
